'use client';
import { Provider } from 'react-redux'
import '@/styles/custom.scss';
import { store } from '@/store/store'
import LayoutComp from '@/components/LayoutComp';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <LayoutComp>
            {children}
          </LayoutComp>
        </Provider>
      </body>
    </html>
  )
}
